"""AI search storage protocols."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class AiSearchStorage(Protocol):
    def create_ai_search_message(self, record: Dict[str, Any]) -> bool: ...
    def list_ai_search_messages(self, task_id: str) -> List[Dict[str, Any]]: ...
    def get_next_ai_search_plan_version(self, task_id: str) -> int: ...
    def create_ai_search_plan(self, record: Dict[str, Any]) -> bool: ...
    def update_ai_search_plan(self, task_id: str, plan_version: int, **kwargs: Any) -> bool: ...
    def get_ai_search_plan(self, task_id: str, plan_version: Optional[int] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_plans(self, task_id: str) -> List[Dict[str, Any]]: ...
    def create_ai_search_run(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_run(self, task_id: str, run_id: Optional[str] = None, *, plan_version: Optional[int] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_runs(self, task_id: str) -> List[Dict[str, Any]]: ...
    def update_ai_search_run(self, task_id: str, run_id: str, **kwargs: Any) -> bool: ...
    def replace_ai_search_retrieval_todos(self, run_id: str, task_id: str, plan_version: int, todos: List[Dict[str, Any]]) -> int: ...
    def list_ai_search_retrieval_todos(self, run_id: str) -> List[Dict[str, Any]]: ...
    def get_ai_search_retrieval_todo(self, run_id: str, todo_id: str) -> Optional[Dict[str, Any]]: ...
    def update_ai_search_retrieval_todo(self, run_id: str, todo_id: str, **kwargs: Any) -> bool: ...
    def create_ai_search_execution_summary(self, record: Dict[str, Any]) -> bool: ...
    def list_ai_search_execution_summaries(self, run_id: str, *, sub_plan_id: str = "") -> List[Dict[str, Any]]: ...
    def create_ai_search_batch(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_batch(self, batch_id: str) -> Optional[Dict[str, Any]]: ...
    def get_latest_ai_search_batch(self, run_id: str, batch_type: str) -> Optional[Dict[str, Any]]: ...
    def update_ai_search_batch(self, batch_id: str, **kwargs: Any) -> bool: ...
    def replace_ai_search_batch_documents(self, batch_id: str, run_id: str, document_ids: List[str]) -> int: ...
    def list_ai_search_batch_documents(self, batch_id: str) -> List[str]: ...
    def create_ai_search_pending_action(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_pending_action(self, task_id: str, action_type: str, *, status: str = "pending") -> Optional[Dict[str, Any]]: ...
    def get_ai_search_pending_action_by_id(self, action_id: str) -> Optional[Dict[str, Any]]: ...
    def get_current_ai_search_pending_action(self, task_id: str, *, statuses: Optional[List[str]] = None) -> Optional[Dict[str, Any]]: ...
    def update_ai_search_pending_action(self, action_id: str, **kwargs: Any) -> bool: ...
    def resolve_ai_search_pending_action(self, action_id: str, *, status: str = "resolved") -> bool: ...
    def get_next_ai_search_execution_queue_ordinal(self, task_id: str, run_id: str) -> int: ...
    def create_ai_search_execution_queue_message(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_execution_queue_message(self, queue_message_id: str) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_execution_queue_messages(self, task_id: str, run_id: str, *, statuses: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...
    def update_ai_search_execution_queue_message(self, queue_message_id: str, **kwargs: Any) -> bool: ...
    def upsert_ai_search_documents(self, records: List[Dict[str, Any]]) -> int: ...
    def list_ai_search_documents(self, task_id: str, plan_version: Any, stages: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...
    def update_ai_search_document(self, task_id: str, plan_version: int, document_id: str, **kwargs: Any) -> bool: ...
    def create_ai_search_document_decision(self, record: Dict[str, Any]) -> bool: ...
    def list_ai_search_document_decisions(self, run_id: str, *, decision_stage: str = "") -> List[Dict[str, Any]]: ...
    def create_ai_search_feature_comparison(self, record: Dict[str, Any]) -> bool: ...
    def list_ai_search_feature_comparisons(self, task_id: str, plan_version: int) -> List[Dict[str, Any]]: ...
    def get_ai_search_feature_comparison(self, task_id: str, plan_version: Any, feature_comparison_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def create_ai_search_close_read_result(self, record: Dict[str, Any]) -> bool: ...
    def get_latest_ai_search_close_read_result(self, run_id: str) -> Optional[Dict[str, Any]]: ...
    def put_ai_search_checkpoint(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_checkpoint(self, thread_id: str, checkpoint_ns: str, checkpoint_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_checkpoints(self, thread_id: str, checkpoint_ns: Optional[str] = None, checkpoint_id: Optional[str] = None, before_checkpoint_id: Optional[str] = None, limit: Optional[int] = None) -> List[Dict[str, Any]]: ...
    def put_ai_search_checkpoint_blobs(self, records: List[Dict[str, Any]]) -> int: ...
    def get_ai_search_checkpoint_blobs(self, thread_id: str, checkpoint_ns: str, versions: Dict[str, Any]) -> Dict[str, str]: ...
    def put_ai_search_checkpoint_writes(self, records: List[Dict[str, Any]]) -> int: ...
    def list_ai_search_checkpoint_writes(self, thread_id: str, checkpoint_ns: str, checkpoint_id: str) -> List[Dict[str, Any]]: ...
    def delete_ai_search_thread_checkpoints(self, thread_id: str) -> bool: ...
