"""AI search storage protocols."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class AiSearchStorage(Protocol):
    def create_ai_search_message(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_message(self, message_id: str) -> Optional[Dict[str, Any]]: ...
    def update_ai_search_message(self, message_id: str, **kwargs: Any) -> bool: ...
    def list_ai_search_messages(self, task_id: str) -> List[Dict[str, Any]]: ...
    def append_ai_search_stream_event(self, record: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_stream_events(self, session_id: str, *, after_seq: int = 0, limit: Optional[int] = None) -> List[Dict[str, Any]]: ...
    def get_latest_ai_search_stream_event(self, session_id: str) -> Optional[Dict[str, Any]]: ...
    def get_next_ai_search_plan_version(self, task_id: str) -> int: ...
    def create_ai_search_plan(self, record: Dict[str, Any]) -> bool: ...
    def update_ai_search_plan(self, task_id: str, plan_version: int, **kwargs: Any) -> bool: ...
    def get_ai_search_plan(self, task_id: str, plan_version: Optional[int] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_plans(self, task_id: str) -> List[Dict[str, Any]]: ...
    def create_ai_search_run(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_run(self, task_id: str, run_id: Optional[str] = None, *, plan_version: Optional[int] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_runs(self, task_id: str) -> List[Dict[str, Any]]: ...
    def update_ai_search_run(self, task_id: str, run_id: str, **kwargs: Any) -> bool: ...
    def upsert_ai_search_documents(self, records: List[Dict[str, Any]]) -> int: ...
    def list_ai_search_documents(self, task_id: str, plan_version: Any, stages: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...
    def update_ai_search_document(self, task_id: str, plan_version: int, document_id: str, **kwargs: Any) -> bool: ...
    def put_ai_search_checkpoint(self, record: Dict[str, Any]) -> bool: ...
    def get_ai_search_checkpoint(self, thread_id: str, checkpoint_ns: str, checkpoint_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def list_ai_search_checkpoints(self, thread_id: str, checkpoint_ns: Optional[str] = None, checkpoint_id: Optional[str] = None, before_checkpoint_id: Optional[str] = None, limit: Optional[int] = None) -> List[Dict[str, Any]]: ...
    def put_ai_search_checkpoint_blobs(self, records: List[Dict[str, Any]]) -> int: ...
    def get_ai_search_checkpoint_blobs(self, thread_id: str, checkpoint_ns: str, versions: Dict[str, Any]) -> Dict[str, str]: ...
    def put_ai_search_checkpoint_writes(self, records: List[Dict[str, Any]]) -> int: ...
    def list_ai_search_checkpoint_writes(self, thread_id: str, checkpoint_ns: str, checkpoint_id: str) -> List[Dict[str, Any]]: ...
    def delete_ai_search_thread_checkpoints(self, thread_id: str) -> bool: ...
