"""System-log protocols."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class SystemLogsStorage(Protocol):
    def insert_system_log(self, record: Dict[str, Any]) -> bool: ...
    def get_system_log(self, log_id: str) -> Optional[Dict[str, Any]]: ...
    def list_system_logs(self, **kwargs: Any) -> Dict[str, Any]: ...
    def summarize_system_logs(self, *, date_from: Optional[str] = None, date_to: Optional[str] = None) -> Dict[str, Any]: ...
    def cleanup_system_logs_before(self, cutoff_iso: str) -> int: ...
    def list_system_log_payload_paths_for_policy_cleanup(self) -> List[str]: ...
    def cleanup_system_logs_by_policy(self) -> int: ...
