"""Task and task-derived analytics protocols."""

from __future__ import annotations

from datetime import date
from typing import Any, Dict, List, Optional, Protocol

from ..models import AccountMonthTarget, Task, TaskStatus


class TaskDomainStorage(Protocol):
    def create_task(self, task: Task) -> Task: ...
    def get_task(self, task_id: str) -> Optional[Task]: ...
    def update_task(self, task_id: str, **kwargs: Any) -> bool: ...
    def delete_task(self, task_id: str) -> bool: ...
    def list_tasks(self, status: Optional[TaskStatus] = None, pn: Optional[str] = None, owner_id: Optional[str] = None, limit: int = 100, offset: int = 0, order_by: str = "created_at", order_desc: bool = True) -> List[Task]: ...
    def list_admin_tasks(self, **kwargs: Any) -> Dict[str, Any]: ...
    def summarize_admin_tasks(self) -> Dict[str, Any]: ...
    def get_admin_task_detail(self, task_id: str) -> Optional[Dict[str, Any]]: ...
    def count_tasks(self, status: Optional[TaskStatus] = None, pn: Optional[str] = None, owner_id: Optional[str] = None) -> int: ...
    def count_user_tasks_today(self, owner_id: str, tz_offset_hours: int = 8, task_type: Optional[str] = None, include_deleted: bool = False, statuses: Optional[List[str]] = None) -> int: ...
    def get_statistics(self) -> Dict[str, Any]: ...
    def record_patent_analysis(self, pn: Optional[str], sha256: Optional[str] = None) -> bool: ...
    def get_patent_analysis_by_pn(self, pn: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def get_patent_analysis_by_sha256(self, sha256: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def cleanup_old_tasks(self, days: int = 365, dry_run: bool = False) -> int: ...
    def vacuum(self) -> None: ...
    def upsert_account_month_target(self, owner_id: str, year: int, month: int, target_count: int) -> AccountMonthTarget: ...
    def get_account_month_target(self, owner_id: str, year: int, month: int) -> Optional[AccountMonthTarget]: ...
    def get_latest_account_month_target_before(self, owner_id: str, year: int, month: int) -> Optional[AccountMonthTarget]: ...
    def count_user_tasks_by_created_range(self, owner_id: str, start_iso: str, end_iso: str, task_type: Optional[str] = None) -> int: ...
    def count_user_tasks_by_completed_range(self, owner_id: str, start_iso: str, end_iso: str, task_type: Optional[str] = None, status: Optional[str] = None) -> int: ...
    def aggregate_user_created_tasks_daily(self, owner_id: str, start_day: date, end_day: date) -> List[Dict[str, Any]]: ...
    def aggregate_user_completed_tasks_daily(self, owner_id: str, start_day: date, end_day: date, task_type: Optional[str] = None, status: Optional[str] = None) -> List[Dict[str, Any]]: ...
