"""Usage-tracking protocols."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class UsageStorage(Protocol):
    def get_task_llm_usage(self, task_id: str) -> Optional[Dict[str, Any]]: ...
    def upsert_task_llm_usage(self, usage: Dict[str, Any]) -> bool: ...
    def list_task_llm_usage_by_last_usage_range(self, start_iso: str, end_iso: str) -> List[Dict[str, Any]]: ...
    def list_admin_usage_table(self, **kwargs: Any) -> Dict[str, Any]: ...
