"""User and auth session protocols."""

from __future__ import annotations

from typing import Optional, Protocol

from ..models import RefreshSession, User


class UserStorage(Protocol):
    def upsert_authing_user(self, user: User) -> User: ...
    def get_user_by_owner_id(self, owner_id: str) -> Optional[User]: ...
    def get_user_by_name(self, name: str) -> Optional[User]: ...
    def upsert_refresh_session(self, session: RefreshSession) -> RefreshSession: ...
    def get_refresh_session(self, token_hash: str) -> Optional[RefreshSession]: ...
    def rotate_refresh_session(self, current_session: RefreshSession, next_session: RefreshSession) -> bool: ...
    def revoke_refresh_session(self, token_hash: str, replaced_by_token_hash: Optional[str] = None) -> bool: ...
    def revoke_refresh_sessions_by_owner(self, owner_id: str) -> int: ...
    def update_user_profile(self, owner_id: str, name: Optional[str], picture: Optional[str]) -> Optional[User]: ...
    def update_user_notification_settings(self, owner_id: str, notification_email_enabled: bool, work_notification_email: Optional[str], personal_notification_email: Optional[str]) -> Optional[User]: ...
    def list_admin_users(self, **kwargs: object) -> dict: ...
    def summarize_admin_users(self) -> dict: ...
