"""WeChat binding and delivery protocols."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from ..models import WeChatBinding, WeChatConversationSession, WeChatDeliveryJob, WeChatFlowSession, WeChatLoginSession


class WeChatStorage(Protocol):
    def create_wechat_login_session(self, session: WeChatLoginSession) -> WeChatLoginSession: ...
    def get_wechat_login_session(self, login_session_id: str) -> Optional[WeChatLoginSession]: ...
    def get_current_wechat_login_session(self, owner_id: str) -> Optional[WeChatLoginSession]: ...
    def list_pending_wechat_login_sessions(self) -> List[WeChatLoginSession]: ...
    def update_wechat_login_session(self, login_session_id: str, **updates: Any) -> Optional[WeChatLoginSession]: ...
    def get_wechat_binding_by_owner(self, owner_id: str) -> Optional[WeChatBinding]: ...
    def get_wechat_binding_by_account(self, bot_account_id: str) -> Optional[WeChatBinding]: ...
    def get_wechat_binding_by_peer(self, bot_account_id: str, wechat_peer_id: str) -> Optional[WeChatBinding]: ...
    def list_active_wechat_bindings(self) -> List[WeChatBinding]: ...
    def upsert_wechat_binding(self, binding: WeChatBinding) -> WeChatBinding: ...
    def update_wechat_binding(self, binding_id: str, **updates: Any) -> Optional[WeChatBinding]: ...
    def disconnect_wechat_binding(self, owner_id: str) -> Optional[WeChatBinding]: ...
    def create_wechat_flow_session(self, flow_session: WeChatFlowSession) -> WeChatFlowSession: ...
    def get_active_wechat_flow_session(self, owner_id: str, flow_type: str) -> Optional[WeChatFlowSession]: ...
    def upsert_wechat_flow_session(self, owner_id: str, flow_type: str, *, current_step: Optional[str], draft_payload: Dict[str, Any], expires_at: Optional[Any], status: str = "active") -> WeChatFlowSession: ...
    def resolve_wechat_flow_session(self, owner_id: str, flow_type: str, status: str = "completed") -> bool: ...
    def get_wechat_conversation_session(self, binding_id: str, peer_id: Optional[str] = None) -> Optional[WeChatConversationSession]: ...
    def upsert_wechat_conversation_session(self, session: WeChatConversationSession) -> WeChatConversationSession: ...
    def update_wechat_conversation_session(self, conversation_id: str, **updates: Any) -> Optional[WeChatConversationSession]: ...
    def create_wechat_delivery_job(self, job: WeChatDeliveryJob) -> WeChatDeliveryJob: ...
    def claim_wechat_delivery_jobs(self, limit: int = 1) -> List[WeChatDeliveryJob]: ...
    def update_wechat_delivery_job(self, delivery_job_id: str, **updates: Any) -> Optional[WeChatDeliveryJob]: ...
